#ifndef _INTR_H_INCLUDED_
#define _INTR_H_INCLUDED_

/* ソフトウエア・割込みベクタの定義 */

#define SOFTVEC_TYPE_NUM (61)

#define INTERRUPT_NO_OFFSET 16
#define SVCall_INTERRUPT_NO (11)
#define PENDSV_INTERRUPT_NO (14)
#define SYSTICK_INTERRUPT_NO (15)
#define EXTI0_INTERRUPT_NO (6 + INTERRUPT_NO_OFFSET)
#define EXTI1_INTERRUPT_NO (7 + INTERRUPT_NO_OFFSET)
#define EXTI2_INTERRUPT_NO (8 + INTERRUPT_NO_OFFSET)
#define EXTI3_INTERRUPT_NO (9 + INTERRUPT_NO_OFFSET)
#define EXTI4_INTERRUPT_NO (10 + INTERRUPT_NO_OFFSET)
#define TIM2_GLOBAL_INTERRUPT_NO 28
#define TIM3_GLOBAL_INTERRUPT_NO (29 + INTERRUPT_NO_OFFSET)
#define TIM4_GLOBAL_INTERRUPT_NO 30
#define I2C1_EV_INTERRUPT_NO (31 + INTERRUPT_NO_OFFSET)
#define I2C1_ER_INTERRUPT_NO (32 + INTERRUPT_NO_OFFSET)
#define SPI1_GLOBAL_INTERRUPT_NO 35
#define SPI2_GLOBAL_INTERRUPT_NO 36
#define USART1_GLOBAL_INTERRUPT_NO (37 + INTERRUPT_NO_OFFSET)
#define USART2_GLOBAL_INTERRUPT_NO (38 + INTERRUPT_NO_OFFSET)
#define USART3_GLOBAL_INTERRUPT_NO (39 + INTERRUPT_NO_OFFSET)
#define DMA2_CH1_GLOBAL_INTERRUPT_NO 56
#define DMA2_CH2_GLOBAL_INTERRUPT_NO 57
#define DMA2_CH3_GLOBAL_INTERRUPT_NO 58
#define OCTOSPI1_GLOBAL_INTERRUPT_NO (71 + INTERRUPT_NO_OFFSET)
#define OCTOSPI2_GLOBAL_INTERRUPT_NO (76 + INTERRUPT_NO_OFFSET)



#endif
