#ifndef _INTR_H_INCLUDED_
#define _INTR_H_INCLUDED_

/* ソフトウエア・割込みベクタの定義 */
#define SOFTVEC_TYPE_NUM (110)

#define INTERRUPT_NO_OFFSET						(16)
#define SVCall_INTERRUPT_NO						(11)
#define PENDSV_INTERRUPT_NO						(14)
#define SYSTICK_INTERRUPT_NO					(15)
#define EXTI0_INTERRUPT_NO						(6 + INTERRUPT_NO_OFFSET)
#define EXTI1_INTERRUPT_NO						(7 + INTERRUPT_NO_OFFSET)
#define EXTI2_INTERRUPT_NO						(8 + INTERRUPT_NO_OFFSET)
#define EXTI3_INTERRUPT_NO						(9 + INTERRUPT_NO_OFFSET)
#define EXTI4_INTERRUPT_NO						(10 + INTERRUPT_NO_OFFSET)
#define DMA1_CH1_GLOBAL_INTERRUPT_NO			(11 + INTERRUPT_NO_OFFSET)
#define DMA1_CH2_GLOBAL_INTERRUPT_NO			(12 + INTERRUPT_NO_OFFSET)
#define DMA1_CH3_GLOBAL_INTERRUPT_NO			(13 + INTERRUPT_NO_OFFSET)
#define DMA1_CH4_GLOBAL_INTERRUPT_NO			(14 + INTERRUPT_NO_OFFSET)
#define DMA1_CH5_GLOBAL_INTERRUPT_NO			(15 + INTERRUPT_NO_OFFSET)
#define DMA1_CH6_GLOBAL_INTERRUPT_NO			(16 + INTERRUPT_NO_OFFSET)
#define DMA1_CH7_GLOBAL_INTERRUPT_NO			(17 + INTERRUPT_NO_OFFSET)
#define TIM15_GLOBAL_INTERRUPT_NO				(24 + INTERRUPT_NO_OFFSET)
#define TIM16_GLOBAL_INTERRUPT_NO				(25 + INTERRUPT_NO_OFFSET)
#define TIM17_GLOBAL_INTERRUPT_NO				(26 + INTERRUPT_NO_OFFSET)
#define TIM2_GLOBAL_INTERRUPT_NO				(28 + INTERRUPT_NO_OFFSET)
#define TIM3_GLOBAL_INTERRUPT_NO				(29 + INTERRUPT_NO_OFFSET)
#define TIM4_GLOBAL_INTERRUPT_NO				(30 + INTERRUPT_NO_OFFSET)
#define TIM5_GLOBAL_INTERRUPT_NO				(50 + INTERRUPT_NO_OFFSET)
#define I2C1_EV_INTERRUPT_NO 					(31 + INTERRUPT_NO_OFFSET)
#define I2C1_ER_INTERRUPT_NO 					(32 + INTERRUPT_NO_OFFSET)
#define I2C2_EV_INTERRUPT_NO 					(33 + INTERRUPT_NO_OFFSET)
#define I2C2_ER_INTERRUPT_NO 					(34 + INTERRUPT_NO_OFFSET)
#define SPI1_GLOBAL_INTERRUPT_NO 				(35 + INTERRUPT_NO_OFFSET)
#define SPI2_GLOBAL_INTERRUPT_NO 				(36 + INTERRUPT_NO_OFFSET)
#define USART1_GLOBAL_INTERRUPT_NO				(37 + INTERRUPT_NO_OFFSET)
#define USART2_GLOBAL_INTERRUPT_NO				(38 + INTERRUPT_NO_OFFSET)
#define USART3_GLOBAL_INTERRUPT_NO				(39 + INTERRUPT_NO_OFFSET)
#define DMA2_CH1_GLOBAL_INTERRUPT_NO 			(56 + INTERRUPT_NO_OFFSET)
#define DMA2_CH2_GLOBAL_INTERRUPT_NO 			(57 + INTERRUPT_NO_OFFSET)
#define DMA2_CH3_GLOBAL_INTERRUPT_NO 			(58 + INTERRUPT_NO_OFFSET)
#define OCTOSPI1_GLOBAL_INTERRUPT_NO			(71 + INTERRUPT_NO_OFFSET)
#define SAI1_GLOBAL_INTERRUPT_NO				(74 + INTERRUPT_NO_OFFSET)
#define OCTOSPI2_GLOBAL_INTERRUPT_NO			(76 + INTERRUPT_NO_OFFSET)

// 割込み優先度の定義
#define INTERRPUT_PRIORITY_5	(5)

/* 割込みハンドラの定義 */
typedef void (*INT_HANDLER)(void);

#endif
