
/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-08-12

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <console.h>
#include <string.h>
#include "stm32l4xx.h"
#include "defines.h"
#include "kozos.h"
#include "interrupt.h"
#include "pin_function.h"
#include "clock.h"
// periferal
#include "octspi.h"
#include "sai.h"
#include "i2c_wrapper.h"
#include "dma.h"
#include "spi.h"
#include "tim.h"
// device
#include "w25q20ew_ctrl.h"
#include "gysfdmaxb.h"
#include "bt_dev.h"
#include "pcm3060.h"
#include "lcd_dev.h"
#include "MSP2807.h"

// manager
#include "wav.h"
#include "cyc.h"
#include "flash_mng.h"
#include "touch_screen.h"
// app
#include "console.h"
#include "sound_app.h"
#include "lcd_app.h"
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===================
**===========================================================================
*/
#if 0
static uint16_t disp_data[MSP2807_DISPLAY_WIDTH*MSP2807_DISPLAY_HEIGHT] = {0};
static const uint16_t white_data[MSP2807_DISPLAY_WIDTH*MSP2807_DISPLAY_HEIGHT] = {0};
static const uint16_t sample[MSP2807_DISPLAY_WIDTH*MSP2807_DISPLAY_HEIGHT] = {
	#include ".\mng\image\lena.hex"	
};
// for test 1 
static int test_tsk1(int argc, char *argv[])
{	
	uint16_t cnt = 0;
	uint32_t i;
	
	// MSP2807 open
	msp2807_open();
	
	while(1) {
		memcpy(disp_data, sample, sizeof(disp_data));
		msp2807_write(disp_data);
		kz_tsleep(1000);
		memset(disp_data, 0xFF, sizeof(disp_data));
		msp2807_write(disp_data);
		kz_tsleep(1000);
	}
	
	return 0;
}
#endif

/* „Ç∑„Çπ„ÉÜ„É†„Éª„Çø„Çπ„ÇØ„Å®„É¶„Éº„Ç∂„Éª„Çø„Çπ„ÇØ„ÅÆËµ∑Âãï */
static int start_threads(int argc, char *argv[])
{
	// periferal initialize
	usart_init();
	i2c_wrapper_init();
	sai_init();
//	tim_init();
	dma_init();
	octospi_init();
	spi_init();
	
	// device initialize
	//bt_dev_init();
	msp2807_init();
	//pcm3060_init();
	//LCD_dev_init();
	//gysfdmaxb_init();
	
	// manager initialize
	wav_init();
	cyc_init();
	flash_mng_init();
	ts_mng_init();
	
	// app initialize
	console_init();
	//sound_app_init();
	//lcd_apl_init();
	test_init();
	
	// command setting
	//bt_dev_set_cmd();
	//sound_app_set_cmd();
	//pcm3060_set_cmd();
	w25q20ew_set_cmd();
	//gysfdmaxb_set_cmd();
	flash_mng_set_cmd();
	
	// flash manager open
	flash_mng_open(FLASH_MNG_KIND_W25Q20EW);
	
	//kz_run(BTN_dev_main, "BTN_dev_main",  2, 0x1000, 0, NULL);
	//kz_run(console_main, "console",  3, 0x1000, 0, NULL);
	//kz_run(LCD_app_main, "LCD_app_main",  3, 0x1000, 0, NULL);
	//kz_run(ctl_main, "ctl_main",  3, 0x1000, 0, NULL);
	//kz_run(ctl_cycmsg_main, "ctl_cycmsg",  3, 0x1000, 0, NULL);
	//kz_run(US_main, "US_main",  8, 0x1000, 0, NULL);
	//kz_run(BT_main, "BT_main",  8, 0x1000, 0, NULL);
	//kz_run(BT_mng_connect_sts, "BT_mng_connect_sts",  8, 0x1000, 0, NULL);
	//kz_run(BT_dev_main, "bt_dev",  8, 0x1000, 0, NULL);
	//kz_run(bluetoothdrv_main, "blue_tooth",  8, 0x200, 0, NULL);
	//kz_run(flash_main, "flash",  2, 0x200, 0, NULL);
	//kz_run(BTN_dev_main, "BTN_dev_main",  3, 0x1000, 0, NULL);
	//kz_run(test_tsk1, "test_tsk1",  3, 0x1000, 0, NULL);

	
	// deprioritize
	kz_chpri(15); 
	
	//CTL_MSG_init();
	
	//INTR_ENABLE;
 	while (1) {
		//TASK_IDLE;
	}
	
	return 0;
}

int main(void)
{	
	// ÉNÉçÉbÉNèâä˙âª
	periferal_clock_init();
	// ÉsÉìê›íËèâä˙âª
	pin_function_init();
	
	// OS ÉXÉ^Å[Ég
	kz_start(start_threads, "idle", 0, 0x1000, 0, NULL);
	
	// Ç±Ç±Ç…ÇÕãAÇ¡ÇƒÇ±Ç»Ç¢
	
	return 0;
}
